#!/usr/bin/env bash
set -euo pipefail

choice=$(yabai -m query --windows \
  | jq -r '.[] | select(.app | endswith("-wrapped") | not) | "\(.id)|\(.app): \(.title)"' \
  | awk -F'|' '{print $2 "\t" $1}' \
  | choose -n 15 -w 120 -f "Monaspace Radon Var" -s 26 -c FF9800 -b 1E1E1E -p "󰖰  Pull window:")

id=$(echo "$choice" | awk '{print $NF}')
app=$(echo "$choice" | awk -F':' '{print $1}' | sed 's/^\[[0-9]*\] //')

if [ -n "$id" ]; then
  current_space=$(yabai -m query --spaces --space | jq '.index')
  yabai -m window "$id" --space "$current_space" || open -a "$app"
fi
