#!/usr/bin/env bash
set -euo pipefail
dir="$1"
osascript -e "tell application \"Hammerspoon\" to execute lua code \"local e=hs.eventtap.event e.newSystemKeyEvent('ILLUMINATION_$(echo "$dir" | tr '[:lower:]' '[:upper:]'),true):post() hs.timer.usleep(10000) e.newSystemKeyEvent('ILLUMINATION_$(echo "$dir" | tr '[:lower:]' '[:upper:]'),false):post()\"" 2>/dev/null || true
